/**
 * @fileoverview RouteRegistry — stores route definitions with two registration paths:
 *
 * 1. **Auto-discovery (primary)** — the decorator discovery plugin scans for
 *    `@Route`-decorated classes at build time and generates
 *    `virtual:decorator-registry/routes`. On `onModuleInit()`, the registry
 *    imports the virtual module and registers all discovered classes.
 *
 * 2. **Manual (fallback)** — `RouterModule.forFeature()` pushes route classes
 *    to a pending queue. On `onModuleInit()`, the registry drains the queue.
 *
 * Both paths merge `@Route` and `@UseGuards` metadata, wrap `render()` as
 * a React component, and register the route definition.
 *
 * @module @stackra/react-router
 * @category Registries
 */

import { Injectable, type OnModuleInit } from '@stackra/ts-container';
import { BaseRegistry } from '@stackra/ts-support';
import type { ComponentType } from 'react';

import type { RouteMetadata } from '@/interfaces/route-metadata.interface';
import type { RouteDefinition } from '@/interfaces/route-definition.interface';
import { getRouteMetadata } from '@/decorators/route.decorator';
import { getGuardsMetadata } from '@/decorators/use-guards.decorator';

/**
 * Registry that stores route definitions collected from `@Route` decorators.
 *
 * Extends `BaseRegistry` for a consistent registry API.
 * Implements `OnModuleInit` to register routes after DI bootstraps.
 */
@Injectable()
export class RouteRegistry extends BaseRegistry<RouteDefinition> implements OnModuleInit {
  /**
   * Initialize the registry — register routes from auto-discovery.
   *
   * Called automatically by the DI container after all providers are resolved.
   */
  async onModuleInit(): Promise<void> {
    await this.registerFromDiscovery();
  }

  /**
   * Try to import the auto-discovered route classes from the virtual module.
   *
   * The virtual module is generated by the decorator discovery plugin at
   * build time. If the plugin isn't configured or no `@Route` classes were
   * found, this silently skips.
   */
  private async registerFromDiscovery(): Promise<void> {
    try {
      const mod = await import(/* @vite-ignore */ 'virtual:decorator-registry/routes');
      const routeClasses: Array<new () => { render(): any }> = mod.ROUTE_CLASSES ?? [];

      for (const RouteClass of routeClasses) {
        this.registerRouteClass(RouteClass);
      }
    } catch {
      // Virtual module not available — auto-discovery not configured.
    }
  }

  /**
   * Register a single `@Route`-decorated class.
   *
   * Reads `@Route` and `@UseGuards` metadata, wraps the `render()` method
   * as a React functional component, and registers the route definition.
   * Skips silently if the route path is already registered (deduplication).
   *
   * @param RouteClass - A class with `@Route` decorator and optional `render()` method
   */
  private registerRouteClass(RouteClass: new () => { render?(): any }): void {
    const metadata: RouteMetadata | undefined = getRouteMetadata(RouteClass);

    if (!metadata) {
      console.warn(
        `[RouteRegistry] Class "${RouteClass.name}" is missing @Route() decorator — skipped.`
      );
      return;
    }

    // Skip if already registered (deduplication between auto-discovery and manual)
    if (this.has(metadata.path)) return;

    // Merge guards: @UseGuards guards first, then @Route({ guards }) guards
    const useGuardsMetadata = getGuardsMetadata(RouteClass) ?? [];
    const routeGuards = metadata.guards ?? [];
    const allGuards = [...useGuardsMetadata, ...routeGuards];

    // Determine component: use metadata.component if provided, otherwise wrap render() method
    let component: ComponentType<any>;

    if (metadata.component) {
      // Component provided in decorator
      component = metadata.component;
    } else {
      // Fallback to render() method
      const instance = new RouteClass();

      if (typeof instance.render !== 'function') {
        console.warn(
          `[RouteRegistry] Class "${RouteClass.name}" has no render() method and no component in @Route() — skipped.`
        );
        return;
      }

      // Wrap the render() method as a React functional component
      component = () => instance.render!();
      component.displayName = RouteClass.name;
    }

    // Register with merged guards
    this.register({ ...metadata, guards: allGuards.length > 0 ? allGuards : undefined }, component);
  }

  /**
   * Register a route definition.
   *
   * Supports two signatures:
   * - `register(metadata, component)` — from decorator flow
   * - `register(key, definition)` — BaseRegistry signature
   */
  override register(
    metadataOrKey: RouteMetadata | string,
    componentOrDefinition: ComponentType<any> | RouteDefinition
  ): void {
    if (typeof metadataOrKey === 'string') {
      super.register(metadataOrKey, componentOrDefinition as RouteDefinition);
    } else {
      const metadata = metadataOrKey;
      const component = componentOrDefinition as ComponentType<any>;
      const definition: RouteDefinition = { ...metadata, component };
      super.register(metadata.path, definition);
    }
  }

  /**
   * Get all registered routes.
   */
  getRoutes(): RouteDefinition[] {
    return this.getAll();
  }

  /**
   * Check if a route path is already registered.
   */
  override has(path: string): boolean {
    return super.has(path);
  }
}
