/**
 * Example: Basic Usage of Decorator Discovery Plugin
 *
 * This example shows how to use the virtual modules generated by the
 * decorator discovery plugin to access decorator metadata at runtime.
 */

// ============================================================================
// 1. Import virtual modules
// ============================================================================

import { MODULE_REGISTRY, getAllModules } from 'virtual:decorator-registry/modules';
import { PROVIDER_REGISTRY, getAllProviders } from 'virtual:decorator-registry/providers';
import { SUBSCRIBER_REGISTRY, getAllSubscribers } from 'virtual:decorator-registry/subscribers';
import { DECORATOR_REGISTRY, getAllDecorators } from 'virtual:decorator-registry/all';

// ============================================================================
// 2. Query modules
// ============================================================================

console.log('=== All Modules ===');
const modules = getAllModules();
modules.forEach((module) => {
  console.log(`- ${module.className} (${module.filePath})`);
  console.log(`  Args:`, module.args);
});

// Find a specific module
const appModule = MODULE_REGISTRY.find((m) => m.className === 'AppModule');
if (appModule) {
  console.log('\n=== AppModule ===');
  console.log('File:', appModule.filePath);
  console.log('Args:', appModule.args);
}

// ============================================================================
// 3. Query providers
// ============================================================================

console.log('\n=== All Providers ===');
const providers = getAllProviders();
providers.forEach((provider) => {
  console.log(`- ${provider.className} (${provider.filePath})`);
});

// Find providers in a specific package
const authProviders = PROVIDER_REGISTRY.filter((p) => p.filePath.includes('packages/auth/'));
console.log('\n=== Auth Providers ===');
authProviders.forEach((provider) => {
  console.log(`- ${provider.className}`);
});

// ============================================================================
// 4. Query subscribers
// ============================================================================

console.log('\n=== All Subscribers ===');
const subscribers = getAllSubscribers();
subscribers.forEach((subscriber) => {
  console.log(`- ${subscriber.className}.${subscriber.methodName ?? 'class'}`);
  console.log(`  Topic:`, subscriber.args[0]);
});

// Find subscribers for a specific topic
const loginSubscribers = SUBSCRIBER_REGISTRY.filter((s) => {
  const topic = s.args[0];
  return typeof topic === 'string' && topic.includes('login');
});
console.log('\n=== Login Subscribers ===');
loginSubscribers.forEach((subscriber) => {
  console.log(`- ${subscriber.className}.${subscriber.methodName}`);
  console.log(`  Topic:`, subscriber.args[0]);
});

// ============================================================================
// 5. Query all decorators
// ============================================================================

console.log('\n=== All Decorators ===');
const allDecorators = getAllDecorators();
console.log(`Total decorators: ${allDecorators.length}`);
console.log(`- Modules: ${DECORATOR_REGISTRY.modules.length}`);
console.log(`- Providers: ${DECORATOR_REGISTRY.providers.length}`);
console.log(`- Subscribers: ${DECORATOR_REGISTRY.subscribers.length}`);

// Query by decorator name
const injectableDecorators = DECORATOR_REGISTRY.providers;
console.log('\n=== @Injectable Decorators ===');
injectableDecorators.forEach((decorator) => {
  console.log(`- ${decorator.className} (${decorator.filePath})`);
});

// ============================================================================
// 6. Custom decorators
// ============================================================================

// If you configured custom decorators in the plugin:
// decoratorDiscoveryPlugin({ customDecorators: ['MyDecorator'] })

const customDecorators = DECORATOR_REGISTRY.custom.get('MyDecorator');
if (customDecorators) {
  console.log('\n=== @MyDecorator ===');
  customDecorators.forEach((decorator) => {
    console.log(`- ${decorator.className} (${decorator.filePath})`);
  });
}

// ============================================================================
// 7. Build a module graph
// ============================================================================

interface ModuleNode {
  name: string;
  imports: string[];
  providers: string[];
  exports: string[];
}

function buildModuleGraph(): Map<string, ModuleNode> {
  const graph = new Map<string, ModuleNode>();

  for (const module of MODULE_REGISTRY) {
    const metadata = module.args[0]; // First arg is the module metadata object

    if (typeof metadata === 'object' && metadata !== null) {
      graph.set(module.className, {
        name: module.className,
        imports: Array.isArray(metadata.imports)
          ? metadata.imports.map((imp: any) => (typeof imp === 'string' ? imp : imp.toString()))
          : [],
        providers: Array.isArray(metadata.providers)
          ? metadata.providers.map((prov: any) =>
              typeof prov === 'string' ? prov : prov.toString()
            )
          : [],
        exports: Array.isArray(metadata.exports)
          ? metadata.exports.map((exp: any) => (typeof exp === 'string' ? exp : exp.toString()))
          : [],
      });
    }
  }

  return graph;
}

const moduleGraph = buildModuleGraph();
console.log('\n=== Module Graph ===');
moduleGraph.forEach((node, name) => {
  console.log(`\n${name}:`);
  console.log(`  Imports: ${node.imports.join(', ') || 'none'}`);
  console.log(`  Providers: ${node.providers.join(', ') || 'none'}`);
  console.log(`  Exports: ${node.exports.join(', ') || 'none'}`);
});

// ============================================================================
// 8. Validate module graph
// ============================================================================

function validateModuleGraph(): string[] {
  const errors: string[] = [];

  for (const module of MODULE_REGISTRY) {
    const metadata = module.args[0];

    if (typeof metadata === 'object' && metadata !== null) {
      // Check if all imported modules exist
      if (Array.isArray(metadata.imports)) {
        for (const imp of metadata.imports) {
          const importName = typeof imp === 'string' ? imp : imp.toString();
          const exists = MODULE_REGISTRY.some((m) => m.className === importName);

          if (!exists) {
            errors.push(
              `Module "${module.className}" imports "${importName}" which does not exist`
            );
          }
        }
      }

      // Check if all providers are registered
      if (Array.isArray(metadata.providers)) {
        for (const prov of metadata.providers) {
          const providerName = typeof prov === 'string' ? prov : prov.toString();
          const exists = PROVIDER_REGISTRY.some((p) => p.className === providerName);

          if (!exists) {
            errors.push(
              `Module "${module.className}" declares provider "${providerName}" which is not @Injectable`
            );
          }
        }
      }
    }
  }

  return errors;
}

const validationErrors = validateModuleGraph();
if (validationErrors.length > 0) {
  console.log('\n=== Validation Errors ===');
  validationErrors.forEach((error) => console.error(`❌ ${error}`));
} else {
  console.log('\n✅ Module graph is valid');
}
