/**
 * Support Env Plugin
 *
 * Vite plugin that automatically bridges `import.meta.env` into
 * `@stackra/ts-support`'s `Env` class and optionally boots global helpers.
 *
 * ## What It Does
 *
 * 1. **Injects a virtual module** (`virtual:stackra-env-boot`) that:
 *    - Calls `Env.setRepository(import.meta.env)` so `env()` reads Vite env vars
 *    - Optionally calls `bootGlobals()` to install global helpers
 *
 * 2. **Prepends the virtual module** to the app's entry point so the
 *    Env repository is configured before any application code runs.
 *
 * ## Why a Plugin?
 *
 * `import.meta.env` is only available inside Vite-processed modules.
 * You can't call `Env.setRepository(import.meta.env)` from a library
 * because the library is pre-built — `import.meta.env` would be `undefined`.
 *
 * This plugin generates a small module **inside the consumer's Vite build**
 * where `import.meta.env` is live, then imports it before the app starts.
 *
 * @module plugins/support-env
 */

import type { Plugin } from 'vite';

import type { ISupportEnvPluginOptions } from '@/interfaces/support-env-plugin-options.interface';
export type { ISupportEnvPluginOptions } from '@/interfaces/support-env-plugin-options.interface';

// ============================================================================
// Virtual Module
// ============================================================================

/**
 * The virtual module ID used internally by Vite.
 * Prefixed with `\0` to mark it as virtual (Vite convention).
 */
const VIRTUAL_MODULE_ID = 'virtual:stackra-env-boot';
const RESOLVED_VIRTUAL_MODULE_ID = '\0' + VIRTUAL_MODULE_ID;

/**
 * Generate the virtual module source code.
 *
 * This code runs inside the consumer's Vite build where
 * `import.meta.env` is live and populated.
 *
 * @param bootGlobals - Whether to include the bootGlobals() call
 * @returns The generated module source code
 */
function generateBootModule(bootGlobals: boolean): string {
  const lines = [
    '/* Auto-generated by @stackra/vite-config — support-env plugin */',
    "import { Env } from '@stackra/ts-support';",
  ];

  if (bootGlobals) {
    lines.push("import { bootGlobals } from '@stackra/ts-support';");
  }

  lines.push('');
  lines.push('/* Bridge Vite env vars into the Env class */');
  lines.push('Env.setRepository(import.meta.env);');

  if (bootGlobals) {
    lines.push('');
    lines.push('/* Install global helpers (env, collect, tap, filled, etc.) */');
    lines.push('bootGlobals();');
  }

  lines.push('');
  return lines.join('\n');
}

// ============================================================================
// Plugin Factory
// ============================================================================

/**
 * Create the support-env Vite plugin.
 *
 * Bridges `import.meta.env` into `@stackra/ts-support`'s `Env` class
 * so that `env('VITE_APP_NAME')` works in Vite projects without
 * manual setup.
 *
 * @param options - Plugin configuration options
 * @returns Configured Vite Plugin instance
 *
 * @example
 * ```typescript
 * // Via defineConfig plugin map (recommended)
 * import { defineConfig } from '@stackra/vite-config';
 *
 * export default defineConfig({
 *   plugins: {
 *     env: true, // or { bootGlobals: false }
 *   },
 * });
 * ```
 *
 * @example
 * ```typescript
 * // Standalone usage
 * import { env } from '@stackra/vite-config';
 *
 * export default {
 *   plugins: [env({ bootGlobals: true })],
 * };
 * ```
 */
export function env(options: ISupportEnvPluginOptions = {}): Plugin {
  const { bootGlobals: shouldBoot = true } = options;

  return {
    name: '@stackra/support-env',

    resolveId(id: string) {
      if (id === VIRTUAL_MODULE_ID) {
        return RESOLVED_VIRTUAL_MODULE_ID;
      }
      return null;
    },

    load(id: string) {
      if (id === RESOLVED_VIRTUAL_MODULE_ID) {
        return generateBootModule(shouldBoot);
      }
      return null;
    },

    transform(code: string, id: string) {
      if (/\/src\/main\.tsx?$/.test(id)) {
        return `import "${VIRTUAL_MODULE_ID}";\n${code}`;
      }
      return null;
    },

    config(_config, { command: _command }) {
      return {
        envPrefix: options.envPrefixes?.length ? [...options.envPrefixes, 'VITE_'] : undefined,
      };
    },
  };
}
