/**
 * Type declarations for @stackra-inc/vite-decorator-discovery
 *
 * This file exports all type declarations for the virtual modules
 * generated by the decorator discovery plugin.
 *
 * ## Usage
 *
 * Add this to your `vite-env.d.ts` or `env.d.ts`:
 *
 * ```typescript
 * /// <reference types="@stackra-inc/vite-decorator-discovery/virtual-modules" />
 * ```
 *
 * Or add to your `tsconfig.json`:
 *
 * ```json
 * {
 *   "compilerOptions": {
 *     "types": ["@stackra-inc/vite-decorator-discovery/virtual-modules"]
 *   }
 * }
 * ```
 *
 * @module @types
 */

/// <reference path="./virtual-modules.d.ts" />

export {};
