/**
 * Type declarations for virtual modules generated by @stackra-inc/vite-decorator-discovery
 *
 * These modules are generated at build time by the Vite plugin and don't exist
 * as physical files. TypeScript needs these declarations to provide type safety
 * and IntelliSense when importing from `virtual:decorator-registry/*`.
 *
 * @module @types/virtual-modules
 */

// ============================================================================
// virtual:decorator-registry/modules
// ============================================================================

declare module 'virtual:decorator-registry/modules' {
  /**
   * Metadata for a @Module decorator.
   */
  export interface ModuleMetadata {
    /** Decorator name (always 'Module') */
    name: string;
    /** Class name that was decorated */
    className: string;
    /** Relative file path from project root */
    filePath: string;
    /** Decorator arguments (parsed from AST) */
    args: any[];
  }

  /**
   * Registry of all @Module decorators discovered in the codebase.
   */
  export const MODULE_REGISTRY: ModuleMetadata[];

  /**
   * Find a module by its class name.
   *
   * @param className - The class name to search for
   * @returns Module metadata or undefined if not found
   */
  export function getModuleByClassName(className: string): ModuleMetadata | undefined;

  /**
   * Get all modules.
   *
   * @returns Array of all module metadata
   */
  export function getAllModules(): ModuleMetadata[];
}

// ============================================================================
// virtual:decorator-registry/providers
// ============================================================================

declare module 'virtual:decorator-registry/providers' {
  /**
   * Metadata for an @Injectable decorator.
   */
  export interface ProviderMetadata {
    /** Decorator name (always 'Injectable') */
    name: string;
    /** Class name that was decorated */
    className: string;
    /** Relative file path from project root */
    filePath: string;
    /** Decorator arguments (parsed from AST) */
    args: any[];
  }

  /**
   * Registry of all @Injectable decorators discovered in the codebase.
   */
  export const PROVIDER_REGISTRY: ProviderMetadata[];

  /**
   * Find a provider by its class name.
   *
   * @param className - The class name to search for
   * @returns Provider metadata or undefined if not found
   */
  export function getProviderByClassName(className: string): ProviderMetadata | undefined;

  /**
   * Get all providers.
   *
   * @returns Array of all provider metadata
   */
  export function getAllProviders(): ProviderMetadata[];
}

// ============================================================================
// virtual:decorator-registry/subscribers
// ============================================================================

declare module 'virtual:decorator-registry/subscribers' {
  /**
   * Metadata for @Subscribe or @AsSubscriber decorators.
   */
  export interface SubscriberMetadata {
    /** Decorator name ('Subscribe' or 'AsSubscriber') */
    name: string;
    /** Class name that was decorated */
    className: string;
    /** Relative file path from project root */
    filePath: string;
    /** Decorator arguments (parsed from AST) */
    args: any[];
    /** Method name (for method-level decorators like @Subscribe) */
    methodName?: string;
  }

  /**
   * Registry of all @Subscribe and @AsSubscriber decorators discovered in the codebase.
   */
  export const SUBSCRIBER_REGISTRY: SubscriberMetadata[];

  /**
   * Find all subscribers for a specific class.
   *
   * @param className - The class name to search for
   * @returns Array of subscriber metadata for the class
   */
  export function getSubscribersByClassName(className: string): SubscriberMetadata[];

  /**
   * Find all subscribers for a specific topic.
   *
   * @param topic - The topic string to search for
   * @returns Array of subscriber metadata for the topic
   */
  export function getSubscribersByTopic(topic: string): SubscriberMetadata[];

  /**
   * Get all subscribers.
   *
   * @returns Array of all subscriber metadata
   */
  export function getAllSubscribers(): SubscriberMetadata[];
}

// ============================================================================
// virtual:decorator-registry/all
// ============================================================================

declare module 'virtual:decorator-registry/all' {
  /**
   * Generic decorator metadata.
   */
  export interface DecoratorMetadata {
    /** Decorator name (e.g., 'Module', 'Injectable', 'Subscribe') */
    name: string;
    /** Class name that was decorated */
    className: string;
    /** Relative file path from project root */
    filePath: string;
    /** Decorator arguments (parsed from AST) */
    args: any[];
    /** Method name (for method-level decorators) */
    methodName?: string;
    /** Unique metadata key (for DiscoveryService.createDecorator pattern) */
    metadataKey?: string;
  }

  /**
   * Combined registry of all decorators.
   */
  export interface DecoratorRegistry {
    /** All @Module decorators */
    modules: DecoratorMetadata[];
    /** All @Injectable decorators */
    providers: DecoratorMetadata[];
    /** All @Subscribe and @AsSubscriber decorators */
    subscribers: DecoratorMetadata[];
    /** Custom decorators grouped by name */
    custom: Map<string, DecoratorMetadata[]>;
  }

  /**
   * Combined registry of all decorators discovered in the codebase.
   */
  export const DECORATOR_REGISTRY: DecoratorRegistry;

  /**
   * Get all decorators with a specific name.
   *
   * @param name - The decorator name to search for
   * @returns Array of decorator metadata
   */
  export function getDecoratorsByName(name: string): DecoratorMetadata[];

  /**
   * Get all decorators (flattened).
   *
   * @returns Array of all decorator metadata
   */
  export function getAllDecorators(): DecoratorMetadata[];
}
